Bag/Bag/urls.py
from django.contrib import admin
from django.urls import path,include
#Static
from . import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GrossaryBag.urls')),
    path('authenticate/',include('authenticate.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Bag/GrossaryBag/urls.py
from django.urls import path
from . import views

app_name = "bag"

urlpatterns = [
    path('',views.home,name="Home"),
    path('add/<int:pk>/',views.add_item,name="add"),
    path('update/<int:pk>/',views.update_item,name="update"),
    path('delete/<int:pk>/',views.delete_item,name="delete"),
    path('check/<int:pk>/',views.check,name="check"),
]

Bag/authenticate/urls.py
from django.urls import path
from . import views

app_name = "authenticate"

urlpatterns = [
    # Signup and login,logout
    path('signup/',views.signup,name='signup'),
    path('login/',views.Login,name="login"),
    path('logout/',views.Logout,name='logout'),
    # Profile
    path('profile/<int:pk>/',views.my_profile,name='profile'),
    path('profile/change/<int:pk>/',views.change_profile,name="change_profile"),
    path('porfile/photo/<int:pk>/',views.change_photo,name="change_photo"),
    path('porfile/password/<int:pk>/',views.ChangePassword,name="change_password"),
]

Bag/GrossaryBag/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class GroceryList(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    item_name = models.CharField(max_length=256)
    item_quantity = models.CharField(max_length=50)
    item_status = models.CharField(max_length=100)
    date = models.DateField()

Bag/GrossaryBag/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
import datetime
# Models import
from django.contrib.auth.models import User
from .models import GroceryList

#login imports
from django.contrib.auth.decorators import login_required
# Https Imports
from django.http import HttpResponse,HttpResponseRedirect

# Create your views here.
@login_required(login_url='/authenticate/login/')
def home(request):

    user = get_object_or_404(User,pk=request.user.pk)
    grossary = GroceryList.objects.filter(user=user,date=str(datetime.date.today()))

    if request.method == "POST":
        filter_date = request.POST.get("date")
        print(datetime.date.today(),filter_date)
        grossary = GroceryList.objects.filter(user=user,date=str(filter_date))
        return render(request,"index.html",context={"grossary":grossary})
    return render(request,"index.html",context={"grossary":grossary})


@login_required(login_url='/authenticate/login/')
def add_item(request,pk):
    user = get_object_or_404(User,pk=pk)
    if request.method == "POST":
        item_name = request.POST.get("item_name")
        item_quantity = request.POST.get("item_quantity")
        item_status = request.POST.get("item_status")
        date = request.POST.get("date")

        add = GroceryList(user=user,item_name=item_name,item_quantity=item_quantity,item_status=item_status,date=date)
        add.save()

        return HttpResponseRedirect(reverse('bag:Home'))
    return render(request,"GrossaryBag/add_item.html")

@login_required(login_url='/authenticate/login/')
def update_item(request,pk):
    grossary = get_object_or_404(GroceryList,pk=pk)
    if request.method == "POST":
        item_name = request.POST.get("item_name")
        item_quantity = request.POST.get("item_quantity")
        item_status = request.POST.get("item_status")
        date = request.POST.get("date")

        # Update
        grossary.item_name = item_name
        grossary.item_quantity = item_quantity
        grossary.item_status = item_status
        grossary.date = date

        grossary.save()

        return HttpResponseRedirect(reverse('bag:Home'))
    return render(request,"GrossaryBag/update_item.html",context={"grossary":grossary})

@login_required(login_url='/authenticate/login/')
def delete_item(request,pk):
    grossary = get_object_or_404(GroceryList,pk=pk)
    grossary.delete()
    return HttpResponseRedirect(reverse('bag:Home'))

@login_required(login_url='/authenticate/login/')
def check(request,pk):
    grossary = get_object_or_404(GroceryList,pk=pk)
    grossary.item_status = "Purchased"
    grossary.save()
    return HttpResponseRedirect(reverse('bag:Home'))

Bag/GrossaryBag/templates/index.html
<!doctype html>
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- CSS -->
	<link href="{% static 'assets/css/index.css' %}" rel="stylesheet">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
<title> Grossary Bag </title>
</head>
<body class="body-bg" style="font-family: 'Roboto', sans-serif;">

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg nav-bg p-4">
 <div class="container-fluid">
  <!-- Brand logo -->
   <a class="navbar-brand nav-text-color nav-brand-size">
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-basket3" viewBox="0 0 16 16">
  <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
</svg>
    </a>
  <!-- End of Brand logo -->

  <!-- Toggler -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>
   <!-- End of Toggler -->

   <!-- Navbar contents -->
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	 <!-- Home -->
	  <li class="nav-item ms-4">
	    <a class="nav-link active nav-text-color" href="{% url 'bag:Home' %}"> Home </a>
      </li>


		 {% if user.is_authenticated %}
          <!-- Profile -->
           <li class="nav-item ms-4">
               <a class="nav-link active nav-text-color" href="{% url 'authenticate:profile' pk=user.pk %}"> Profile </a>
           </li>

          {% endif %}
	 </ul>

	 <form class="d-flex" method="POST">
         {% csrf_token %}
        <input class="form-control me-2 text-muted" type="date" name="date">
        <button class="btn nav-text-color btn-outline-success" type="submit">Filter</button>
      </form>
       {% if user.is_authenticated %}
       <!-- Logout -->
          <li class="nav-item mb-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:logout' %}"> Logout </a>
          </li>
       {% else %}
       <li class="nav-item ms-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:login'  %}"> Login </a>
          </li>
       {% endif %}
   </div>
   <!-- End of navbar contents -->


 </div>
</nav>
<!-- End of Navigation Bar -->

<!-- Start of Body -->
<div class="container">
  <div class="row">
   <div class="col">
    <!-- Title -->

	<div class="mt-4">
        <h2 class="fst-italic"> Today's Gorssary List</h2>
	</div>
       <div class="add_item text-end fst-italic">
           <a href="{% url 'bag:add' pk=user.pk %}" class="add-item" style="font-size: 1.8rem;text-decoration: none;">
               <span class="pe-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                       <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                       <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                      </svg>
               </span>Add Item</a>
       </div>
	<!-- End of title -->

	<div class="row g-4 mt-4">
	<!-- Start of cards -->
  {% for i in grossary %}
	<div class="col-4" style="width: 18rem;">
     <div class="card">
	  <div class="card-body">
	   <h2>{{ i.item_name }}</h2>
	   <hr>
	   <p class="card-text">{{ i.item_quantity }}</p>
	   <p class="card-text">{{ i.item_status }}</p>

	   <div class="d-flex justify-content-around">
	     <a href="{% url 'bag:update' pk=i.pk %}" class="btn btn-outline-primary">Update Item</a>
         <a href="{% url 'bag:check' pk=i.pk %}" class="btn btn-outline-primary">Purchased</a>
	   </div>

	  </div>
	 </div>
	</div>
        {% empty %}
        <h2 class="fst-italic">No, Grossary's Today!!</h2>
        {% endfor %}
	<!-- End of cards -->

	   </div>

	  </div>
	 </div>
	</div>
	<!-- End of cards -->
	</div>

   </div>
  </div>
</div>
<!-- End of Body -->





 <!-- Option 1: Bootstrap Bundle with Popper -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

</body>
</html>